name: Collect and Upload IP Info

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # 每两小时运行一次（UTC时间）

permissions:
  contents: write

jobs:
  process-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 更新到v4版本

    - name: Delete old data
      run: |
        rm -rf ./ip*
        rm -rf ./ips

    - name: Get source data
      run: |
        wget -N https://zip.cm.edu.kg -O ip.zip
        unzip ip.zip -d ./ips
        rm ip.zip

    - name: Set up Python
      uses: actions/setup-python@v4  # 更新Python设置Action
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests pandas tqdm

    - name: Run IP info collector
      run: python ip_info_collector.py

    - name: Set upload script permissions
      run: chmod +x ips_to_cfkv.sh

    - name: Upload files to Cloudflare
      env:
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
      run: |
        # 使用脚本上传文件
        ./ips_to_cfkv.sh

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "自动更新IP信息文件"
        git push
